export const REPORT_SECTIONS = [
  {
    title: 'Purchase Reports',
    iconKey: 'LocalShipping',
    color: '#16A34A',
    reports: [
      { key: 'receipt_register', name: 'Receipt Register', description: 'All receipt challans' },
      { key: 'vendor_purchase', name: 'Vendor Purchase', description: 'Vendor-wise purchases' },
      { key: 'vendor_returns', name: 'Vendor Returns', description: 'Return to vendor register' },
      { key: 'purchase_history', name: 'Purchase History', description: 'Item-wise receipt history with avg rate' },
    ],
  },
  {
    title: 'Issue Reports',
    iconKey: 'Business',
    color: '#D97706',
    reports: [
      { key: 'issue_register', name: 'Issue Register', description: 'All issue challans' },
      { key: 'department_wise', name: 'Department Wise', description: 'Consumption by department' },
      { key: 'transfer_register', name: 'Transfer Register', description: 'Stock transfers between locations' },
      { key: 'central_store_summary', name: 'Central Store Summary', description: 'Store stock & issue breakdown with KPIs' },
    ],
  },
  {
    title: 'Inventory Reports',
    iconKey: 'Inventory',
    color: '#2563EB',
    reports: [
      { key: 'stock_ledger', name: 'Stock Ledger', description: 'Complete stock movement ledger' },
      { key: 'stock_summary', name: 'Stock Summary', description: 'Current stock levels by item' },
      { key: 'item_history', name: 'Item History', description: 'Transaction history per item' },
      { key: 'movement_register', name: 'Movement Register', description: 'All stock movements' },
      { key: 'dharamshala_items', name: 'Dharamshala Items', description: 'Items in dharamshala rooms' },
      { key: 'department_stock_status', name: 'Department Stock Status', description: 'Current stock in department and rooms' },
      { key: 'current_stock_custom', name: 'Current Stock', description: 'Store-wise current stock with value' },
      { key: 'stock_distribution', name: 'Stock Distribution', description: 'Store/Dharamshala/Room wise stock breakdown' },
      { key: 'dharamshala_distribution', name: 'Dharamshala Distribution', description: 'Dharamshala-level stock & room allocation' },
      { key: 'room_facilities', name: 'Room Facilities Checklist', description: 'Installed assets per room' },
      { key: 'item_audit_ledger', name: 'Item Audit Ledger', description: 'Complete item movement history' },
      { key: 'item_lifecycle', name: 'Item Lifecycle', description: 'Chronological movement history of an item' },
    ],
  },
  {
    title: 'Analytics Reports',
    iconKey: 'Analytics',
    color: '#7C3AED',
    reports: [
      { key: 'visual_analytics', name: 'Visual Analytics', description: 'Interactive charts and graphs' },
      { key: 'low_stock', name: 'Low Stock Items', description: 'Items below minimum level' },
      { key: 'dead_stock', name: 'Dead Stock', description: 'Items with no movement' },
      { key: 'damage_report', name: 'Damage Report', description: 'Damaged items report' },
      { key: 'stock_adjustments', name: 'Stock Adjustments', description: 'All adjustments made' },
      { key: 'audit_log', name: 'Audit Log', description: 'System activity log' },
      { key: 'damage_scrap_returns', name: 'Damage/Scrap/Returns', description: 'Damage, scrap & vendor return audit' },
    ],
  },
  {
    title: 'Enterprise Reports',
    iconKey: 'Business',
    color: '#0EA5E9',
    reports: [
      { key: 'store_wise_stock', name: 'Store-wise Stock', description: 'Stock levels across all stores' },
      { key: 'installation_tracking', name: 'Installation Tracking', description: 'Installed assets by store/room' },
    ],
  },
  {
    title: 'Stock Analysis Reports',
    iconKey: 'Assessment',
    color: '#059669',
    reports: [
      { key: 'overall_stock', name: 'Overall Stock', description: 'Company-wide stock totals per item' },
      { key: 'dept_stock', name: 'Department Stock', description: 'Department-wise stock grouped by store' },
      { key: 'item_stock', name: 'Item Stock', description: 'Item-wise stock across all stores' },
      { key: 'category_stock', name: 'Category Stock', description: 'Category-level aggregated stock totals' },
    ],
  },
  {
    title: 'Movement Reports',
    iconKey: 'SwapHoriz',
    color: '#DC2626',
    reports: [
      { key: 'uninstallation_report', name: 'Uninstallation Report', description: 'All uninstallation transactions' },
      { key: 'repair_report', name: 'Repair Report', description: 'All repair transactions' },
      { key: 'replacement_report', name: 'Replacement Report', description: 'All replacement transactions' },
      { key: 'return_report', name: 'Return Report', description: 'All return transactions' },
    ],
  },
  {
    title: 'Ledger Reports',
    iconKey: 'MenuBook',
    color: '#7C2D12',
    reports: [
      { key: 'item_ledger', name: 'Item Ledger', description: 'Full ledger filtered by item' },
      { key: 'store_ledger', name: 'Store Ledger', description: 'Full ledger filtered by store' },
      { key: 'dept_ledger', name: 'Department Ledger', description: 'Full ledger for department stores' },
    ],
  },
  {
    title: 'Asset Reports',
    iconKey: 'DevicesOther',
    color: '#4338CA',
    reports: [
      { key: 'asset_register', name: 'Asset Register', description: 'Full asset profile list' },
      { key: 'installed_assets', name: 'Installed Assets', description: 'Active installed assets' },
      { key: 'asset_health', name: 'Asset Health', description: 'Asset health metrics and scores' },
      { key: 'warranty_expiry', name: 'Warranty Expiry', description: 'Assets with expiring warranties' },
      { key: 'amc_expiry', name: 'AMC Expiry', description: 'Active AMC agreements expiring soon' },
    ],
  },
  {
    title: 'Purchase Analysis Reports',
    iconKey: 'ShoppingCart',
    color: '#B45309',
    reports: [
      { key: 'purchase_register', name: 'Purchase Register', description: 'All purchase orders with details' },
      { key: 'grn_register', name: 'GRN Register', description: 'All Goods Receipt Notes' },
      { key: 'vendor_performance', name: 'Vendor Performance', description: 'Per-vendor metrics and ratings' },
    ],
  },
  {
    title: 'Maintenance Reports',
    iconKey: 'Build',
    color: '#9333EA',
    reports: [
      { key: 'service_register', name: 'Service Register', description: 'Maintenance history with costs' },
      { key: 'wo_register', name: 'Work Order Register', description: 'All work orders with details' },
      { key: 'downtime_report', name: 'Downtime Report', description: 'Breakdown history and causes' },
      { key: 'repair_cost', name: 'Repair Cost', description: 'Aggregated repair costs per asset' },
    ],
  },
  {
    title: 'Financial Reports',
    iconKey: 'AccountBalance',
    color: '#1E40AF',
    reports: [
      { key: 'inventory_valuation', name: 'Inventory Valuation', description: 'Per-item valuation with avg rate' },
      { key: 'import_history', name: 'Import History', description: 'All import history records' },
      { key: 'transaction_summary', name: 'Transaction Summary', description: 'Transaction count by voucher type' },
    ],
  },
];

export const REPORT_NAMES: Record<string, string> = {};
REPORT_SECTIONS.forEach((s) => s.reports.forEach((r) => { REPORT_NAMES[r.key] = r.name; }));

export const TX_TYPES = [
  { value: 'RECEIPT', label: 'Receipt' },
  { value: 'PURCHASE', label: 'Purchase' },
  { value: 'ISSUE', label: 'Issue' },
  { value: 'TRANSFER_IN', label: 'Transfer In' },
  { value: 'TRANSFER_OUT', label: 'Transfer Out' },
  { value: 'ADJUSTMENT_IN', label: 'Adjustment In' },
  { value: 'ADJUSTMENT_OUT', label: 'Adjustment Out' },
  { value: 'DAMAGE', label: 'Damage' },
  { value: 'OPENING_BALANCE', label: 'Opening Stock' },
  { value: 'VENDOR_RETURN', label: 'Vendor Return' },
  { value: 'RETURN_IN', label: 'Return In' },
  { value: 'RETURN_OUT', label: 'Return Out' },
  { value: 'REVERSAL', label: 'Reversal' },
  { value: 'CONSUMPTION_OUT', label: 'Consumption' },
  { value: 'CONSUMPTION_REVERSAL', label: 'Consumption Reversal' },
  { value: 'SCRAP_OUT', label: 'Scrap' },
  { value: 'INSTALL_OUT', label: 'Install' },
  { value: 'UNINSTALL_OUT', label: 'Uninstall' },
];

export const ADJUSTMENT_TYPES = [
  { value: 'ADD', label: 'Addition' },
  { value: 'SUBTRACT', label: 'Subtraction' },
  { value: 'CORRECTION', label: 'Correction' },
];

export const AUDIT_ACTIONS = [
  { value: 'CREATE', label: 'Created' },
  { value: 'UPDATE', label: 'Updated' },
  { value: 'DELETE', label: 'Deleted' },
  { value: 'POST', label: 'Posted' },
  { value: 'CANCEL', label: 'Cancelled' },
  { value: 'LOGIN', label: 'Logged In' },
  { value: 'LOGOUT', label: 'Logged Out' },
  { value: 'EXPORT', label: 'Exported' },
  { value: 'IMPORT', label: 'Imported' },
  { value: 'BACKUP', label: 'Backup' },
  { value: 'RESTORE', label: 'Restored' },
];

export const EXCLUDE_KEYS = [
  'id', 'uuid', 'companyId', 'financialYearId', 'categoryId', 'unitId', 'vendorId',
  'departmentId', 'locationId', 'parentId', 'receiptChallanId', 'issueChallanId',
  'transferChallanId', 'vendorReturnChallanId', 'assetInstallationId', 'originalReceiptId',
  'createdAt', 'updatedAt', 'cancelledAt', 'postedAt', 'sourceStoreId',
  'isActive', 'isClosed', 'closedAt', 'minimumStockLevel', 'categoryId',
];

export const COLUMN_LABELS: Record<string, string> = {
  challanNo: 'Challan No', sourceType: 'Source', sourceName: 'Source Name',
  invoiceNumber: 'Invoice No', invoiceDate: 'Invoice Date', vehicleNumber: 'Vehicle No',
  receivedBy: 'Received By', issuedBy: 'Issued By', approvedBy: 'Approved By',
  transferredBy: 'Transferred By', returnedBy: 'Returned By', reportedBy: 'Reported By',
  adjustedBy: 'Adjusted By', createdBy: 'Created By', transactionType: 'Type',
  transactionDate: 'Date', quantityIn: 'Qty In', quantityOut: 'Qty Out',
  balanceQty: 'Balance', referenceType: 'Ref Type', referenceNo: 'Ref No',
  departmentType: 'Dept Type', departmentName: 'Department', itemName: 'Item',
  itemCode: 'Code', locationType: 'Location Type', locationName: 'Location',
  totalAmount: 'Total', purpose: 'Purpose', remarks: 'Remarks', adjustmentType: 'Type',
  reason: 'Reason', installedDate: 'Installed', installedBy: 'Installed By',
  totalQty: 'Total Received', rooms: 'Room No (Qty)',
  returned: 'Returned', parentLocation: 'Parent Location',
  status: 'Status', totalReceived: 'Received', totalIssued: 'Issued',
  currentStock: 'Current Stock', lastMovement: 'Last Movement', name: 'Name',
  username: 'Username', action: 'Action', tableName: 'Table', description: 'Description',
  oldValues: 'Old Values', newValues: 'New Values',
  item: 'Item Name', department: 'Department', location: 'Location',
  source: 'Source', destination: 'Destination',
  vendor: 'Vendor', items: 'Items',
  quantity: 'Qty', amount: 'Amount', unitName: 'Unit', postedAt: 'Posted At',
  categoryName: 'Category',
  storeName: 'Store', storeType: 'Store Type', totalItems: 'Total Items',
  totalQuantity: 'Total Qty', roomName: 'Room',
  uninstalledDate: 'Uninstalled', uninstalledBy: 'Uninstalled By',
  deficit: 'Deficit', minimumLevel: 'Min Level', stockStatus: 'Status',
  lastRate: 'Last Rate',
  healthScore: 'Health Score',
  repairCount: 'Repairs',
  totalRepairCost: 'Repair Cost',
  warrantyEnd: 'Warranty End',
  amcEnd: 'AMC End',
  totalPO: 'Total POs',
  completedGRN: 'Completed GRNs',
  avgRating: 'Avg Rating',
  labourCost: 'Labour Cost',
  materialCost: 'Material Cost',
  vendorCost: 'Vendor Cost',
  avgRate: 'Avg Rate',
  value: 'Value',
  voucherType: 'Voucher Type',
  txCount: 'Count',
};

export const REPORT_FILTER_MAP: Record<string, string[]> = {
  receipt_register: ['date', 'vendor', 'store', 'status', 'search'],
  issue_register: ['date', 'department', 'status', 'search'],
  stock_ledger: ['date', 'item', 'store', 'department', 'txType', 'search'],
  current_stock_custom: ['store', 'department', 'category', 'search'],
  stock_distribution: ['item', 'category', 'store', 'department', 'location', 'search'],
  stock_summary: ['store', 'department', 'category', 'search'],
  low_stock: ['item', 'category', 'store', 'lowStock', 'search'],
  dead_stock: ['item', 'category', 'store', 'search'],
  damage_report: ['date', 'item', 'store', 'location', 'status', 'search'],
  department_wise: ['date', 'item', 'department', 'txType', 'search'],
  department_stock_status: ['department', 'search'],
  vendor_purchase: ['date', 'vendor', 'search'],
  item_history: ['date', 'item', 'store', 'department', 'search'],
  movement_register: ['date', 'item', 'store', 'department', 'txType', 'search'],
  transfer_register: ['date', 'department', 'search'],
  vendor_returns: ['date', 'vendor', 'search'],
  purchase_history: ['date', 'item', 'category', 'search'],
  stock_adjustments: ['date', 'item', 'adjustmentType', 'search'],
  audit_log: ['date', 'auditFilters', 'search'],
  dharamshala_items: ['search'],
  central_store_summary: ['store', 'department', 'category', 'date', 'search'],
  dharamshala_distribution: ['department', 'search'],
  room_facilities: ['store', 'department', 'location', 'search'],
  item_audit_ledger: ['item', 'date', 'search'],
  item_lifecycle: ['item', 'search'],
  visual_analytics: ['search'],
  damage_scrap_returns: ['date', 'category', 'search'],
  store_wise_stock: ['item', 'category', 'search'],
  installation_tracking: ['item', 'store', 'search'],
  overall_stock: ['category', 'search'],
  dept_stock: ['department', 'search'],
  item_stock: ['item', 'category', 'search'],
  category_stock: ['category', 'search'],
  uninstallation_report: ['date', 'item', 'search'],
  repair_report: ['date', 'item', 'search'],
  replacement_report: ['date', 'item', 'search'],
  return_report: ['date', 'item', 'search'],
  item_ledger: ['item', 'date', 'search'],
  store_ledger: ['store', 'date', 'search'],
  dept_ledger: ['department', 'date', 'search'],
  asset_register: ['store', 'search'],
  installed_assets: ['item', 'store', 'search'],
  asset_health: ['search'],
  warranty_expiry: ['search'],
  amc_expiry: ['search'],
  purchase_register: ['date', 'vendor', 'search'],
  grn_register: ['date', 'vendor', 'search'],
  vendor_performance: ['search'],
  service_register: ['date', 'item', 'search'],
  wo_register: ['date', 'search'],
  downtime_report: ['date', 'item', 'search'],
  repair_cost: ['search'],
  inventory_valuation: ['category', 'search'],
  import_history: ['date', 'search'],
  transaction_summary: ['date', 'search'],
};
