export const DEMO_DHARAMSHALAS = [
  {
    name: "à¤…à¤¤à¤¿à¤µà¥€à¤° à¤…à¤¤à¤¿à¤¥à¤¿ à¤—à¥ƒà¤¹",
    rooms: [
      { name: "Room 1 - NON A.C. ROOM 4 BED", floor: "FF", category: "NON A.C. ROOM 4 BED" },
      { name: "Room 1 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 2 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 3 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 4 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 5 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 6 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 7 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 8 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 9 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 10 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 11 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 12 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 13 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 14 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 15 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 16 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 17 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 18 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 19 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
      { name: "Room 20 - NON AC SINGLE BED", floor: "GF", category: "NON AC SINGLE BED" },
    ],
  },
  {
    name: "à¤…à¤¤à¤¿à¤µà¥€à¤° à¤—à¥‡à¤¸à¥à¤Ÿ à¤¹à¤¾à¤‰à¤¸",
    rooms: [
      { name: "Room 2 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 3 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 4 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 5 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 6 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 7 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
    ],
  },
  {
    name: "à¤¬à¤¾à¤œà¤¾à¤° à¤¬à¥€ à¤¬à¥à¤²à¤¾à¤•",
    rooms: [
      { name: "Room 3 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 4 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 6 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 7 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 8 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 12 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 13 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 14 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 15 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 16 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 2 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 5 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 9 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 10 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 11 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
    ],
  },
  {
    name: "à¤•à¤Ÿà¤²à¤¾ à¤šà¤¾à¤‚à¤¦à¤¨à¥€",
    rooms: [
      { name: "Room 131 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 132 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 133 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 134 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 135 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 136 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 137 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 138 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 139 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
    ],
  },
  {
    name: "à¤•à¤Ÿà¤²à¤¾ à¤‰à¤¤à¥à¤¤à¤°à¥€ à¤µà¤¿à¤‚à¤—",
    rooms: [
      { name: "Room 50 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 51 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 52 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 57 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 109 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 110 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 111 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 112 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 113 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 114 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 115 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 116 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 117 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 118 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 119 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 120 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 121 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 122 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 123 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 124 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 125 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 126 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 127 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 128 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 47 - A.C. DELUXE 4 BED", floor: "GF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 48 - NON AC 2 BED", floor: "GF", category: "NON AC 2 BED" },
      { name: "Room 54 - NON AC 2 BED", floor: "GF", category: "NON AC 2 BED" },
      { name: "Room 55 - NON AC 2 BED", floor: "GF", category: "NON AC 2 BED" },
      { name: "Room 56 - NON AC 2 BED", floor: "GF", category: "NON AC 2 BED" },
      { name: "Room 46 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 49 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 58 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 59 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
    ],
  },
  {
    name: "à¤•à¤Ÿà¤²à¤¾ à¤ªà¥‚à¤°à¥à¤µà¥€ à¤µà¤¿à¤‚à¤—",
    rooms: [
      { name: "Room 39 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 40 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 41 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 42 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 43 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 44 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 45 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 103 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 104 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 105 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 106 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 107 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 108 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
    ],
  },
  {
    name: "à¤•à¤Ÿà¤²à¤¾ à¤¦à¤•à¥à¤·à¤¿à¤£ à¤µà¤¿à¤‚à¤—",
    rooms: [
      { name: "Room 26 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 27 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 28 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 29 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 30 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 31 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 32 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 34 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 35 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 37 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 38 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 79 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 80 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 81 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 82 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 83 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 84 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 85 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 87 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 88 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 89 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 90 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 91 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 92 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 93 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 94 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 95 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 96 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 97 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 98 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 78 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 1 - A.C. HALL 10 BED", floor: "FF", category: "A.C. HALL 10 BED" },
    ],
  },
  {
    name: "à¤•à¤Ÿà¤²à¤¾ à¤ªà¤¶à¥à¤šà¤¿à¤® à¤µà¤¿à¤‚à¤—",
    rooms: [
      { name: "Room 2 - A.C. DELUXE 4 BED", floor: "GF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 4 - A.C. DELUXE 4 BED", floor: "GF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 6 - A.C. DELUXE 4 BED", floor: "GF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 15 - A.C. DELUXE 4 BED", floor: "GF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 63 - A.C. DELUXE 3 BED", floor: "FF", category: "A.C. DELUXE 3 BED" },
      { name: "Room 64 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 66 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 70 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 71 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 72 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 73 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 68 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 67 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 69 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
    ],
  },
  {
    name: "à¤•à¥à¤¨à¥à¤¦ à¤•à¥à¤¨à¥à¤¦ à¤¨à¤¿à¤²à¤¯",
    rooms: [
      { name: "Room 1 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 2 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 3 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 4 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 5 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 6 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 8 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 9 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 10 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 11 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 12 - NON A.C. ROOM 2 BED", floor: "BMT", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 13 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 14 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 15 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 16 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 17 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 18 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 19 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 21 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 22 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 23 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 24 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 25 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 26 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 28 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 29 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 30 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 31 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 32 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 33 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 34 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 36 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 37 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 38 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 39 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 40 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 41 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 7 - NON A.C.HALL 6 BED", floor: "BMT", category: "NON A.C.HALL 6 BED" },
      { name: "Room 20 - NON A.C.HALL 6 BED", floor: "GF", category: "NON A.C.HALL 6 BED" },
      { name: "Room 27 - NON A.C.HALL 6 BED", floor: "GF", category: "NON A.C.HALL 6 BED" },
      { name: "Room 35 - NON A.C.HALL 6 BED", floor: "FF", category: "NON A.C.HALL 6 BED" },
      { name: "Room 42 - NON A.C.HALL 6 BED", floor: "FF", category: "NON A.C.HALL 6 BED" },
    ],
  },
  {
    name: "à¤²à¤¾à¤²à¤¾ à¤‰à¤®à¤°à¤¾à¤µ à¤¸à¤¿à¤¹ à¤œà¥ˆà¤¨",
    rooms: [
      { name: "Room 102 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 103 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 104 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 105 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 106 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 108 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 109 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 110 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 111 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 201 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 202 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 203 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 204 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 205 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 206 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 207 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 209 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 210 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 211 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 212 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 301 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 302 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 303 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 304 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 305 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 306 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 307 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 309 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 310 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 311 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 312 - A.C. DELUXE 2 BED", floor: "SF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 401 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 402 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 403 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 404 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 405 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 406 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 407 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 409 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 410 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 411 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 412 - A.C. DELUXE 2 BED", floor: "TF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 501 - A.C. DELUXE 2 BED", floor: "4F", category: "A.C. DELUXE 2 BED" },
      { name: "Room 502 - A.C. DELUXE 2 BED", floor: "4F", category: "A.C. DELUXE 2 BED" },
      { name: "Room 503 - A.C. DELUXE 2 BED", floor: "4F", category: "A.C. DELUXE 2 BED" },
      { name: "Room 208 - A.C. DELUXE 4 BED", floor: "FF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 308 - A.C. DELUXE 4 BED", floor: "SF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 408 - A.C. DELUXE 4 BED", floor: "TF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 504 - A.C. DELUXE 4 BED", floor: "4F", category: "A.C. DELUXE 4 BED" },
      { name: "Room 101 - A.C. DELUXE 2 BED", floor: "GF", category: "A.C. DELUXE 2 BED" },
    ],
  },
  {
    name: "à¤•à¤Ÿà¤²à¤¾ à¤°à¤¥à¤–à¤¾à¤¨à¤¾",
    rooms: [
      { name: "Room 1 - A.C. HALL 6 BED", floor: "FF", category: "A.C. HALL 6 BED" },
      { name: "Room 2 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 3 - A.C. HALL 4 BED", floor: "FF", category: "A.C. HALL 4 BED" },
    ],
  },
  {
    name: "à¤µà¤°à¥à¤§à¤®à¤¾à¤¨",
    rooms: [
      { name: "Room 102 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 103 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 104 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 105 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 106 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 107 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 108 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 109 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 110 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 111 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 114 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 115 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 116 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 117 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 118 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 119 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 120 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 121 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 122 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 202 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 203 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 204 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 205 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 206 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 207 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 208 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 209 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 210 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 214 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 215 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 216 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 217 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 218 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 219 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 220 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 221 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 222 - A.C. DELUXE 2 BED", floor: "FF", category: "A.C. DELUXE 2 BED" },
      { name: "Room 101 - A.C. DELUXE 4 BED", floor: "GF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 123 - A.C. DELUXE 4 BED", floor: "GF", category: "A.C. DELUXE 4 BED" },
      { name: "Room 113 - A.C. HALL 6 BED", floor: "GF", category: "A.C. HALL 6 BED" },
      { name: "Room 201 - A.C. HALL 6 BED", floor: "FF", category: "A.C. HALL 6 BED" },
      { name: "Room 211 - A.C. HALL 6 BED", floor: "FF", category: "A.C. HALL 6 BED" },
      { name: "Room 213 - A.C. HALL 6 BED", floor: "FF", category: "A.C. HALL 6 BED" },
      { name: "Room 223 - A.C. HALL 6 BED", floor: "FF", category: "A.C. HALL 6 BED" },
      { name: "Room 112 - A.C. HALL 12 BED", floor: "GF", category: "A.C. HALL 12 BED" },
      { name: "Room 212 - A.C. HALL 12 BED", floor: "FF", category: "A.C. HALL 12 BED" },
      { name: "Room GH - GUEST HOUSE 4 BED", floor: "1", category: "GUEST HOUSE 4 BED" },
    ],
  },
  {
    name: "à¤¸à¤¨à¥à¤®à¤¤à¤¿",
    rooms: [
      { name: "Room 1 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 2 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 9 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 10 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 11 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 12 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 13 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 14 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 15 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 16 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 17 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 18 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 19 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 20 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 21 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 22 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 23 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 24 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 25 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 26 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 27 - NON A.C. ROOM 2 BED", floor: "GF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 44 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 45 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 52 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 53 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 54 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 55 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 57 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 58 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 59 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 60 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 61 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 62 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 63 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 64 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 65 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 66 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 67 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 68 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 69 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 70 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 72 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 73 - NON A.C. ROOM 2 BED", floor: "FF", category: "NON A.C. ROOM 2 BED" },
      { name: "Room 28 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 29 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 30 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 31 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 32 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 33 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 34 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 35 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 36 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 37 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 38 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 39 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 40 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 41 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 42 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 43 - A.C. ROOM 2 BED", floor: "GF", category: "A.C. ROOM 2 BED" },
      { name: "Room 74 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 75 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 76 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 77 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 78 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 79 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 80 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 81 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 82 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 83 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 84 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 85 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 86 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 87 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 88 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 89 - A.C. ROOM 2 BED", floor: "FF", category: "A.C. ROOM 2 BED" },
      { name: "Room 90 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 91 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 92 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 93 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 94 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 95 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 96 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 97 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 98 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 99 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 100 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 101 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 102 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 103 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 104 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
      { name: "Room 105 - A.C. ROOM 2 BED", floor: "SF", category: "A.C. ROOM 2 BED" },
    ],
  },
  {
    name: "à¤µà¥ˆà¤¶à¤¾à¤²à¥€ à¤¯à¤¾à¤¤à¥à¤°à¥€ à¤¨à¤¿à¤µà¤¾à¤¸",
    rooms: [
      { name: "Room C - NON AC SINGLE BED", floor: "1", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "2", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "3", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "4", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "5", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "6", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "7", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "8", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "9", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "10", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "11", category: "NON AC SINGLE BED" },
      { name: "Room C - NON AC SINGLE BED", floor: "12", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "1", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "3", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "4", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "5", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "6", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "7", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "8", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "9", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "10", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "11", category: "NON AC SINGLE BED" },
      { name: "Room D - NON AC SINGLE BED", floor: "12", category: "NON AC SINGLE BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "1", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "2", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "3", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "4", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "5", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "6", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "7", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "8", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "9", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "10", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "11", category: "NON AC HALL 16 BED" },
      { name: "Room A - NON AC HALL 16 BED", floor: "12", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "1", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "2", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "3", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "4", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "5", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "6", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "7", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "8", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "9", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "10", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "11", category: "NON AC HALL 16 BED" },
      { name: "Room B - NON AC HALL 16 BED", floor: "12", category: "NON AC HALL 16 BED" },
    ],
  },
  {
    name: "à¤šà¤°à¤£ à¤šà¤¿à¤¨à¥à¤¹à¥",
    rooms: [
      { name: "Room 46 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 47 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 49 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 50 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 51 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 52 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 53 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 54 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 55 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 57 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 59 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 60 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 61 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 62 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 111 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 112 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 113 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 114 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 115 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 116 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 117 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 118 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 120 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 121 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 122 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 123 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 124 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 125 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 126 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 127 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 128 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 129 - SEMI DELUXE 2 BED", floor: "GF", category: "SEMI DELUXE 2 BED" },
      { name: "Room 119 - SEMI DELUXE HALL 2 BED", floor: "GF", category: "SEMI DELUXE HALL 2 BED" },
      { name: "Room 130 - SEMI DELUXE HALL 2 BED", floor: "GF", category: "SEMI DELUXE HALL 2 BED" },
      { name: "Room 65 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 66 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 67 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 68 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 69 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 70 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 72 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 73 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 74 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 75 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 76 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 77 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 78 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 79 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 80 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 81 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 82 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 85 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 86 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 87 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 88 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 89 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 90 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 91 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 92 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 93 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 94 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 95 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 97 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 98 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 99 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 100 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 101 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 105 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 106 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 109 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 110 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 1 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 5 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 8 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 12 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 13 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 14 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 15 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 28 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 30 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 31 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 33 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 2 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 3 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 4 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 7 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 9 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 10 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 11 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 16 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 17 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 18 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 19 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 20 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 21 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 22 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 23 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 24 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 25 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 26 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 27 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 29 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 32 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 34 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 35 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 36 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 37 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 38 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 39 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 40 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 41 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 42 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 43 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
      { name: "Room 44 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 45 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 48 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 56 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 58 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 63 - SEMI DELUXE 2 BED", floor: "BMT", category: "SEMI DELUXE 2 BED" },
      { name: "Room 64 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 71 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 83 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 84 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 96 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 102 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 103 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 104 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 107 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 108 - GENERAL NON ATTACH", floor: "GF", category: "GENERAL NON ATTACH" },
      { name: "Room 131 - SEMI DELUXE HALL 2 BED", floor: "GF", category: "SEMI DELUXE HALL 2 BED" },
      { name: "Room 6 - GENERAL NON ATTACH", floor: "BMT", category: "GENERAL NON ATTACH" },
    ],
  },
  {
    name: "à¤µà¤°à¥à¤§à¤®à¤¾à¤¨ à¤—à¥‡à¤¸à¥à¤Ÿ à¤¹à¤¾à¤‰à¤¸",
    rooms: [
      { name: "Room 1 - A.C. DELUXE Hall", floor: "GF", category: "A.C. DELUXE Hall" },
    ],
  },
  {
    name: "à¤°à¤¾à¤·à¥à¤Ÿà¥à¤°à¤ªà¤¤à¤¿ à¤­à¤µà¤¨",
    rooms: [
      { name: "Room 1 - A.C. DELUXE Hall", floor: "SF", category: "A.C. DELUXE Hall" },
    ],
  },
  {
    name: "à¤®à¤‚à¤¦à¤¿à¤°",
    rooms: [
      { name: "à¤®à¥à¤–à¥à¤¯ à¤®à¤£à¥à¤¡à¤ª", floor: "Ground", category: "Temple" },
      { name: "à¤—à¤°à¥à¤­à¤—à¥ƒà¤¹", floor: "Ground", category: "Sanctum" },
      { name: "à¤ªà¥à¤°à¤¸à¤¾à¤¦ à¤•à¤•à¥à¤·", floor: "Ground", category: "Kitchen" },
    ],
  },
  {
    name: "à¤§à¤°à¥à¤®à¤¶à¤¾à¤²à¤¾",
    rooms: [
      { name: "Room 1 - à¤®à¥à¤–à¥à¤¯ à¤•à¤•à¥à¤·", floor: "Ground", category: "Main" },
      { name: "Room 2 - à¤­à¤£à¥à¤¡à¤¾à¤°", floor: "Ground", category: "Storage" },
      { name: "Room 3 - à¤…à¤¤à¤¿à¤¥à¤¿ à¤•à¤•à¥à¤·", floor: "First", category: "Guest" },
    ],
  },
  {
    name: "à¤­à¥‹à¤œà¤¨à¤¶à¤¾à¤²à¤¾",
    rooms: [
      { name: "à¤°à¤¸à¥‹à¤ˆ à¤•à¤•à¥à¤·", floor: "Ground", category: "Kitchen" },
      { name: "à¤­à¥‹à¤œà¤¨ à¤•à¤•à¥à¤·", floor: "Ground", category: "Dining" },
      { name: "à¤­à¤£à¥à¤¡à¤¾à¤° à¤•à¤•à¥à¤·", floor: "Ground", category: "Storage" },
    ],
  },
  {
    name: "à¤œà¤² à¤ªà¥à¤²à¤¾à¤‚à¤Ÿ",
    rooms: [
      { name: "à¤ªà¥à¤²à¤¾à¤‚à¤Ÿ à¤•à¤•à¥à¤·", floor: "Ground", category: "Plant" },
      { name: "à¤•à¤¾à¤°à¥à¤¯à¤¾à¤²à¤¯", floor: "Ground", category: "Office" },
    ],
  },
  {
    name: "à¤¶à¥à¤°à¥€ à¤¦à¤¿à¤—à¤‚à¤¬à¤° à¤œà¥ˆà¤¨ à¤…à¤¤à¤¿à¤¶à¤¯ à¤•à¥à¤·à¥‡à¤¤à¥à¤°",
    rooms: [
      { name: "Room 101 - à¤ªà¥à¤°à¤¾à¤°à¥à¤¥à¤¨à¤¾ à¤•à¤•à¥à¤·", floor: "Ground", category: "Temple" },
      { name: "Room 102 - à¤­à¤£à¥à¤¡à¤¾à¤° à¤•à¤•à¥à¤·", floor: "Ground", category: "Storage" },
      { name: "Room 201 - à¤…à¤¤à¤¿à¤¥à¤¿ à¤•à¤•à¥à¤·", floor: "First", category: "Guest" },
      { name: "Room 202 - à¤…à¤¤à¤¿à¤¥à¤¿ à¤•à¤•à¥à¤·", floor: "First", category: "Guest" },
    ],
  },
];
